Feat-coingecko/price-bridge
DZapIO/dzap-sdk pull request #83
Opened 2024-11-28 17:43 UTC by Kiranchaudhary537

2024-12-03 06:26 UTC, manraj2712 requested changes

2024-12-03 06:26 UTC, manraj2712 commented on src/utils/getDecimals.ts
> +export const getDecimalsFromBridge = (
not required

2024-12-03 06:26 UTC, manraj2712 commented on src/utils/getDecimals.ts
> +export const getDecimals = (
not required

2024-12-03 06:26 UTC, manraj2712 commented on src/utils/bridgeQuoteUpdate.ts
> +  const tokensWithoutPrice: Record<number, string[]> = {};
rather create a Record<number, Set[]> rather than creating a set everytime

2024-12-03 06:26 UTC, manraj2712 commented on src/utils/bridgeQuoteUpdate.ts
> +      if (data.srcAmountUSD && data.destAmountUSD) continue;
fees updation check?

2024-12-03 06:26 UTC, manraj2712 commented on src/utils/bridgeQuoteUpdate.ts
> +  return quotes;
path updation?

2024-12-03 06:26 UTC, manraj2712 commented on src/service/price/provider/coingecko/index.ts
> +    const responses = (await Promise.all(requests)) as Record<string, { usd: number }>[];
it should be promise.allSettled

2024-12-03 06:26 UTC, manraj2712 commented on src/service/price/provider/coingecko/index.ts
> +      console.log({ erc20Prices, nativePrice });
remove log

2024-12-03 06:26 UTC, manraj2712 commented on src/service/price/provider/coingecko/index.ts
> +  private fetchERC20Prices = async (chainId: number, addresses: string[], chainConfig: ChainData | null): Promise<Record<string, number>> => {
chainConfig should not be null, if we are reaching this function call

2024-12-03 06:26 UTC, manraj2712 commented on src/service/price/provider/coingecko/index.ts
> +export class CoingeckoPriceProvider {
chainConfig should not be null

2024-12-03 06:26 UTC, manraj2712 commented on src/service/price/priceService.ts
> +  getPriceForTokens = async (chainId: number, tokenAddresses: string[], chainConfig: ChainData | null): Promise<Record<string, string | null>> => {
chainConfig null

2024-12-03 06:26 UTC, manraj2712 commented on src/service/price/priceService.ts
> +      const tokenPrices = await fetchTokenPrice([tokenAddress], chainId);
we should not get price from backend again here, as we are updating the quotes coming from backend itself

2024-12-03 06:26 UTC, manraj2712 commented on src/service/price/priceService.ts
> +      const tokenPrices = await fetchTokenPrice(tokenAddresses, chainId);
do not fetch price again from backend

2024-12-06 04:12 UTC, Kiranchaudhary537 commented on src/service/price/priceService.ts
> +      const tokenPrices = await fetchTokenPrice([tokenAddress], chainId);
This method will be used by frontend to get price not by quotes.

2024-12-06 04:16 UTC, Kiranchaudhary537 commented on src/service/price/priceService.ts
> +      const tokenPrices = await fetchTokenPrice(tokenAddresses, chainId);
This method will be used by frontend to get price. there is other method getPricesFromProvider to get price from coingecko.

2024-12-06 04:22 UTC, Kiranchaudhary537 commented on src/utils/bridgeQuoteUpdate.ts
> +  return quotes;
line no:87

2024-12-06 05:26 UTC, Kiranchaudhary537 commented on src/service/price/priceService.ts
> +      const tokenPrices = await fetchTokenPrice(tokenAddresses, chainId);
This method used by frontend. if price is null from backend then it will backend from coingecko. it's not used by quotes

2024-12-06 05:44 UTC, Kiranchaudhary537 commented on src/utils/swapQuoteUpdate.ts
> +      const srcAmountUSD = BigNumber(srcAmount).multipliedBy(srcTokenPricePerUnit);
For better multiplication handle for big number

2024-12-06 05:46 UTC, Kiranchaudhary537 commented on src/utils/bridgeQuoteUpdate.ts
> +  const tokensWithoutPrice: Record<number, string[]> = {};
It create once for every quote request. this will increase for loop for tokens for converting to array, vice-verse

2024-12-16 07:32 UTC, manraj2712 requested changes

2024-12-16 07:32 UTC, manraj2712 commented on src/service/price/provider/coingecko/index.ts
> +  public getPriceFromCoingecko = async (tokenAddresses: string[], chainId: number, chainConfig: ChainData) => {
rename as getPrice and create a common interface which every pricing provider will use

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/checkUsdExistForToken.ts
> +  if (!data.srcAmountUSD || !data.destAmountUSD) return false;
add path usd check and rename it to isUSDPriceAvailableForQuotes

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/index.ts
> +export const calculateAmountUSD = (amountInWei: string, decimals: number | null, price: string | null) => {
create amount.ts file in utils and move this function there

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/tokens.ts
> +export const getDZapNativeTokenByChainId = (chainId: number) => {
fetch this from backend after updating it in there

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/updateBridgeQuotes.ts
> +  const updateAmountUSD = (feeItem: any, chainId: number, address: string, amount: string, decimals: number) => {
any -> feeDetails

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/updateBridgeQuotes.ts
> +        break;
should be continue instead of break, as we have to include path data checking as well

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/updateBridgeQuotes.ts
> +      if (data.srcAmountUSD && data.destAmountUSD) {
duplicate code

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/updateBridgeQuotes.ts
> +      const hasNativeToken = nativeTokens.some((token) => tokensWithoutPrice[request.fromChain]?.has(token));
remove this

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/updateBridgeQuotes.ts
> +  chainConfig: ChainData | null,
flow should not reach here if chainConfig is null

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/updateSwapQuotes.ts
> +  chainConfig: ChainData | null,
flow should not reach here if chainConfig is null

2024-12-16 07:32 UTC, manraj2712 commented on src/utils/updateSwapQuotes.ts
> +      if (tokensWithoutPrice.includes(zeroAddress)) {
remove this

2024-12-16 12:30 UTC, manraj2712 requested changes

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/IPriceService.ts
> +  fetchPrices(chainId: number, tokenAddresses: string[], chainConfig?: ChainData): Promise<Record<string, string | null>>;
allowedSources and notAllowedSources, also make them named parameters

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/index.ts
> +export const PRICE_PROVIDER_TYPE = {
casing fix

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/index.ts
> +export const PRICE_PROVIDER_PRIORITY_TYPE = {
PricePriority

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/index.ts
> +export const ALL_PROVIDERS: PriceProviderType[] = Object.values(PRICE_PROVIDER_TYPE);
AllPriceProviders

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/index.ts
> +export const EXTERNAL_PROVIDERS: PriceProviderType[] = ALL_PROVIDERS.filter((provider) => provider !== PRICE_PROVIDER_TYPE.DZAP);
ExternalPriceProviders

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/priceService.ts
> +  private createProviderMap(): Map<PriceProviderType, IPriceService> {
createProvidersMap

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/priceService.ts
> +    priorityType = PRICE_PROVIDER_PRIORITY_TYPE.DEFAULT,
remove priority

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/priceService.ts
> +    allowedProviders = ALL_PROVIDERS,
allowedSources, notAllowedSources

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/priceService.ts
> +    const remainingTokens = new Set(tokenAddresses);
no need for additional set

2024-12-16 12:30 UTC, manraj2712 commented on src/service/price/provider/coingecko/index.ts
> +export class CoingeckoPriceProvider implements IPriceService {
rename IPriceService -> IPriceProvider

2024-12-16 12:30 UTC, manraj2712 commented on src/utils/tokens.ts
> +export const nativeTokens: string[] = [
not used now, can be removed

2024-12-16 12:30 UTC, manraj2712 commented on src/utils/updateBridgeQuotes.ts
> +      if (isUSDPriceAvailableForQuotes(data)) {
remove this, and check and update amounts

2024-12-16 12:30 UTC, manraj2712 commented on src/utils/updateSwapQuotes.ts
> +      if (isUSDPriceAvailableForQuotes(data)) {
remove this, and check and update amounts

2024-12-16 13:13 UTC, Kiranchaudhary537 commented on src/utils/updateBridgeQuotes.ts
> +      if (isUSDPriceAvailableForQuotes(data)) {
It's used coingecko used: **isNativeCurrency** which used export const isNativeCurrency = (contract: string) => nativeTokens.includes(contract);

2024-12-17 05:21 UTC, manraj2712 approved these changes

2024-12-17 05:21 UTC, merged