Feat: pricing for tokenlist
DZapIO/dzap-sdk pull request #85
Opened 2024-12-20 11:53 UTC by Kiranchaudhary537

2024-12-20 12:03 UTC, manraj2712 requested changes

2024-12-21 04:00 UTC, manraj2712 requested changes

2024-12-21 04:00 UTC, manraj2712 commented on src/utils/tokens.ts
> +  const tokensWithoutPrice = Object.values(tokens)
filter only those with balance !== '0' and balanceInUSD === null || balanceInUSD === '0'

2024-12-21 04:11 UTC, Kiranchaudhary537 commented on src/utils/tokens.ts
> +  const tokensWithoutPrice = Object.values(tokens)
we only need to filter which has balance but not price.

2024-12-21 04:16 UTC, manraj2712 requested changes

2024-12-21 04:16 UTC, manraj2712 commented on src/utils/tokens.ts
> +    const tokensWithoutPrice = Object.values(tokens)
need to check balanceInUsdc as well

2024-12-21 05:34 UTC, manraj2712 approved these changes

2024-12-21 05:34 UTC, merged